/**
 * Constant labelled examples for personal vs shared expense classification.
 * Each entry: { text, type }
 */
const CLASSIFICATION_EXAMPLES = [
  { text: 'Weekly groceries at Shufersal for the apartment', type: 'shared' },
  { text: 'Electricity bill split with partner', type: 'shared' },
  { text: 'Water and gas utilities payment', type: 'shared' },
  { text: 'Internet subscription for home', type: 'shared' },
  { text: 'Rent payment for shared apartment', type: 'shared' },
  { text: 'Mortgage payment couple home', type: 'shared' },
  { text: 'Supermarket run Rami Levy household items', type: 'shared' },
  { text: 'Cleaning supplies for home', type: 'shared' },
  { text: 'Furniture for living room', type: 'shared' },
  { text: 'Home insurance premium', type: 'shared' },
  { text: 'Property tax payment', type: 'shared' },
  { text: 'Shared Netflix subscription', type: 'shared' },
  { text: 'Joint Spotify family plan', type: 'shared' },
  { text: 'Couple dinner at restaurant', type: 'shared' },
  { text: 'Date night restaurant bill', type: 'shared' },
  { text: 'Groceries for weekend cooking together', type: 'shared' },
  { text: 'Baby supplies diapers formula', type: 'shared' },
  { text: 'Pet food and vet for family dog', type: 'shared' },
  { text: 'Household repairs plumber', type: 'shared' },
  { text: 'Air conditioner maintenance', type: 'shared' },
  { text: 'Municipal arnona property tax', type: 'shared' },
  { text: 'Building committee vaad bayit fee', type: 'shared' },
  { text: 'Shared vacation hotel booking', type: 'shared' },
  { text: 'Flight tickets family trip', type: 'shared' },
  { text: 'Car insurance shared vehicle', type: 'shared' },
  { text: 'Gas fill-up family car', type: 'shared' },
  { text: 'Parking for shared car', type: 'shared' },
  { text: 'Kitchen appliances microwave', type: 'shared' },
  { text: 'Bed sheets and towels home', type: 'shared' },
  { text: 'Garden supplies and plants', type: 'shared' },
  { text: 'Home security system monthly', type: 'shared' },
  { text: 'Landline phone home', type: 'shared' },
  { text: 'Mobile family plan three lines', type: 'shared' },
  { text: 'Daycare childcare payment', type: 'shared' },
  { text: 'School supplies for kids', type: 'shared' },
  { text: 'After-school activities children', type: 'shared' },
  { text: 'Family health insurance premium', type: 'shared' },
  { text: 'Pharmacy medicine for household', type: 'shared' },
  { text: 'Bulk Costco household shopping', type: 'shared' },
  { text: 'שופרסל קניות שבועיות לבית', type: 'shared' },
  { text: 'חשבון חשמל דו חודשי', type: 'shared' },
  { text: 'חשבון מים וארנונה', type: 'shared' },
  { text: 'שכירות דירה משותפת', type: 'shared' },
  { text: 'רמי לוי קניות למשק בית', type: 'shared' },
  { text: 'ארוחת ערב זוגית במסעדה', type: 'shared' },
  { text: 'Netflix מנוי משפחתי', type: 'shared' },
  { text: 'תיקון מזגן בבית', type: 'shared' },
  { text: 'דמי ועד בית', type: 'shared' },
  { text: 'ביטוח דירה', type: 'shared' },
  { text: 'קניות לילדים בגדים', type: 'shared' },
  { text: 'Office team lunch split', type: 'shared' },
  { text: 'Coworking space shared desk', type: 'shared' },
  { text: 'Household laundry detergent', type: 'shared' },
  { text: 'Shared Amazon Prime household', type: 'shared' },
  { text: 'Wedding anniversary dinner', type: 'shared' },
  { text: 'Shared storage unit rental', type: 'shared' },
  { text: 'Home wifi router upgrade', type: 'shared' },
  { text: 'Shared grocery delivery Wolt family', type: 'shared' },
  { text: 'Household light bulbs replacement', type: 'shared' },
  { text: 'Shared Disney Plus family', type: 'shared' },
  { text: 'Home cleaning service monthly', type: 'shared' },
  { text: 'Couple gym membership family plan', type: 'shared' },
  { text: 'Shared heating oil winter', type: 'shared' },
  { text: 'Household trash bags bulk', type: 'shared' },
  { text: 'Shared IKEA furniture assembly items', type: 'shared' },
  { text: 'Shared pest control service', type: 'shared' },
  { text: 'Shared solar panel maintenance', type: 'shared' },
  { text: 'Shared hot water heater repair', type: 'shared' },
  { text: 'Shared lawn mowing service', type: 'shared' },
  { text: 'Shared chimney sweep annual', type: 'shared' },
  { text: 'Shared home alarm monitoring', type: 'shared' },
  { text: 'Shared water filter replacement', type: 'shared' },
  { text: 'Shared dishwasher repair', type: 'shared' },
  { text: 'Shared washing machine purchase', type: 'shared' },
  { text: 'Shared refrigerator replacement', type: 'shared' },
  { text: 'Shared smoke detector batteries', type: 'shared' },
  { text: 'Shared curtain rods and blinds', type: 'shared' },
  { text: 'Shared vacuum cleaner purchase', type: 'shared' },
  { text: 'Shared door lock smart home', type: 'shared' },
  { text: 'Shared compost bin garden', type: 'shared' },
  { text: 'Shared fire extinguisher home safety', type: 'shared' },
  { text: 'Shared mailbox renovation', type: 'shared' },
  { text: 'Shared roof leak repair', type: 'shared' },
  { text: 'Shared gate remote replacement', type: 'shared' },
  { text: 'Shared intercom system apartment', type: 'shared' },
  { text: 'Shared balcony furniture set', type: 'shared' },
  { text: 'Shared kitchen renovation tiles', type: 'shared' },
  { text: 'Shared bathroom renovation shower', type: 'shared' },
  { text: 'Shared driveway paving', type: 'shared' },
  { text: 'Shared fence repair backyard', type: 'shared' },
  { text: 'Shared pool maintenance chemicals', type: 'shared' },
  { text: 'Shared attic insulation upgrade', type: 'shared' },
  { text: 'Shared garage door opener', type: 'shared' },
  { text: 'Shared septic tank pumping', type: 'shared' },
  { text: 'Shared window screen replacement', type: 'shared' },
  { text: 'Shared gutter cleaning service', type: 'shared' },
  { text: 'Shared termite inspection home', type: 'shared' },
  { text: 'Shared mold remediation bathroom', type: 'shared' },
  { text: 'Shared foundation crack repair', type: 'shared' },
  { text: 'Shared radon test kit home', type: 'shared' },
  { text: 'Shared sump pump replacement', type: 'shared' },
  { text: 'Shared earthquake retrofitting', type: 'shared' },
  { text: 'Shared water softener salt bags', type: 'shared' },
  { text: 'Shared backup generator fuel', type: 'shared' },
  { text: 'Shared storm shutter installation', type: 'shared' },
  { text: 'Shared crawl space vapor barrier', type: 'shared' },
  { text: 'Shared whole house fan install', type: 'shared' },
  { text: 'Shared driveway snow removal', type: 'shared' },
  { text: 'Shared home battery backup Powerwall', type: 'shared' },
  { text: 'Shared EV charger installation garage', type: 'shared' },
  { text: 'Shared smart thermostat Nest household', type: 'shared' },
  { text: 'Shared water heater anode rod', type: 'shared' },
  { text: 'Shared whole home air purifier', type: 'shared' },
  { text: 'Shared garage epoxy floor coating', type: 'shared' },
  { text: 'Shared home theater projector mount', type: 'shared' },
  { text: 'Shared whole house water filtration', type: 'shared' },
  { text: 'Shared smart doorbell Ring household', type: 'shared' },
  { text: 'Shared central vacuum service', type: 'shared' },
  { text: 'Shared home automation hub Matter', type: 'shared' },
  { text: 'Shared backup water supply tank', type: 'shared' },
  { text: 'Shared home network mesh WiFi', type: 'shared' },
  { text: 'Shared smart irrigation controller lawn', type: 'shared' },
  { text: 'Shared home battery monitoring service', type: 'shared' },
  { text: 'Shared driveway heated cables snow', type: 'shared' },
  { text: 'Shared attic ladder replacement', type: 'shared' },
  { text: 'Shared home radon mitigation fan', type: 'shared' },
  { text: 'Shared whole house humidifier pad', type: 'shared' },
  { text: 'Shared garage door spring replacement', type: 'shared' },
  { text: 'Shared home backup internet Starlink', type: 'shared' },
  { text: 'Shared driveway gravel delivery', type: 'shared' },
  { text: 'Shared home intercom upgrade video', type: 'shared' },
  { text: 'Shared whole house fan shutter', type: 'shared' },
  { text: 'Shared smart lock battery pack bulk', type: 'shared' },
  { text: 'Shared home water leak detector sensors', type: 'shared' },
  { text: 'Shared attic insulation blower rental', type: 'shared' },
  { text: 'Shared garage storage shelving units', type: 'shared' },
  { text: 'Shared home CO detector replacement pack', type: 'shared' },
  { text: 'Shared driveway pressure washing service', type: 'shared' },
  { text: 'Shared home backup power transfer switch', type: 'shared' },
  { text: 'Shared smart blinds motor kit living room', type: 'shared' },
  { text: 'Shared whole house fan remote replacement', type: 'shared' },
  { text: 'Shared home EV level 2 charger cable', type: 'shared' },
  { text: 'Shared attic pull down ladder install', type: 'shared' },
  { text: 'Shared garage floor mat set cars', type: 'shared' },
  { text: 'Shared home backup generator maintenance', type: 'shared' },
  { text: 'Shared driveway crack filler bulk', type: 'shared' },
  { text: 'Shared attic vent fan thermostat', type: 'shared' },
  { text: 'Shared garage door weather seal kit', type: 'shared' },
  { text: 'Shared home mesh WiFi node extra bedroom', type: 'shared' },
  { text: 'Shared driveway oil stain remover', type: 'shared' },
  { text: 'Shared attic radiant barrier install', type: 'shared' },
  { text: 'Shared garage ceiling storage rack', type: 'shared' },
  { text: 'Shared home backup battery expansion module', type: 'shared' },
  { text: 'Shared driveway reseal DIY materials', type: 'shared' },
  { text: 'Shared attic stair insulation cover', type: 'shared' },
  { text: 'Shared garage door keypad replacement', type: 'shared' },
  { text: 'Shared home backup generator propane tank exchange', type: 'shared' },
  { text: 'Shared driveway snow melt pellets bulk bag', type: 'shared' },
  { text: 'Shared attic access panel replacement', type: 'shared' },
  { text: 'Shared garage door insulation kit panels', type: 'shared' },
  { text: 'Shared home backup inverter transfer kit', type: 'shared' },
  { text: 'Shared driveway edge restraints paver', type: 'shared' },
  { text: 'Shared attic baffle vent chutes pack', type: 'shared' },
  { text: 'Shared garage door bottom seal replacement', type: 'shared' },
  { text: 'Shared home backup battery monitoring app subscription household', type: 'shared' },
  { text: 'Shared driveway heated mat walkway', type: 'shared' },
  { text: 'Shared attic stair cover tent insulation', type: 'shared' },
  { text: 'Shared garage door torsion spring kit', type: 'shared' },
  { text: 'Shared home backup generator oil change kit', type: 'shared' },
  { text: 'Shared driveway crack repair caulk tube bulk', type: 'shared' },
  { text: 'Shared attic fan humidistat control', type: 'shared' },
  { text: 'Shared garage door opener belt drive replacement', type: 'shared' },
  { text: 'Shared home backup battery firmware update service', type: 'shared' },
  { text: 'Shared driveway sealant applicator rental', type: 'shared' },
  { text: 'Shared attic pull cord replacement kit', type: 'shared' },
  { text: 'Shared garage door safety sensor alignment kit', type: 'shared' },
  { text: 'Shared home backup generator cover outdoor', type: 'shared' },
  { text: 'Shared driveway expansion joint filler', type: 'shared' },
  { text: 'Shared attic ladder hinge repair kit', type: 'shared' },
  { text: 'Shared garage door remote control replacement pair', type: 'shared' },
  { text: 'Shared home backup battery wall cable management kit', type: 'shared' },
  { text: 'Shared driveway curb ramp rubber pair', type: 'shared' },
  { text: 'Shared attic stair tent zipper replacement', type: 'shared' },
  { text: 'Shared garage door lubrication maintenance kit', type: 'shared' },
  { text: 'Shared home backup generator wheel kit mobility', type: 'shared' },
  { text: 'Shared driveway paint striping stencil kit', type: 'shared' },
  { text: 'Shared attic baffle staple gun rental', type: 'shared' },
  { text: 'Shared garage door weather stripping side kit', type: 'shared' },
  { text: 'Shared home backup battery expansion cable kit', type: 'shared' },
  { text: 'Shared driveway oil absorbent granules bucket', type: 'shared' },
  { text: 'Shared attic radiant barrier tape roll', type: 'shared' },
  { text: 'Shared garage door hinge replacement set heavy duty', type: 'shared' },
  { text: 'Shared home backup generator muffler replacement', type: 'shared' },
  { text: 'Shared driveway crack router rental tool', type: 'shared' },
  { text: 'Shared attic vent turbine replacement', type: 'shared' },
  { text: 'Shared garage door cable replacement pair', type: 'shared' },
  { text: 'Shared home backup battery monitoring display wall mount', type: 'shared' },
  { text: 'Shared driveway heated cable kit complete', type: 'shared' },
  { text: 'Shared attic stair insulation tent large', type: 'shared' },
  { text: 'Shared garage door roller replacement nylon set', type: 'shared' },
  { text: 'Shared home backup generator fuel stabilizer treatment', type: 'shared' },
  { text: 'Shared driveway sealcoat squeegee tool set', type: 'shared' },
  { text: 'Shared attic fan motor capacitor replacement', type: 'shared' },
  { text: 'Shared garage door strut reinforcement kit', type: 'shared' },
  { text: 'Shared home backup battery vent kit wall pass through', type: 'shared' },
  { text: 'Shared driveway crack filler applicator bottle bulk', type: 'shared' },
  { text: 'Shared attic access ladder folding aluminum', type: 'shared' },
  { text: 'Shared garage door bottom bracket replacement pair', type: 'shared' },
  { text: 'Shared home backup generator spark plug set', type: 'shared' },
  { text: 'Shared driveway heated mat controller replacement', type: 'shared' },
  { text: 'Shared attic baffle foam chute pack 50 count', type: 'shared' },
  { text: 'Shared garage door opener chain drive sprocket kit', type: 'shared' },
  { text: 'Shared home backup battery ground rod kit', type: 'shared' },
  { text: 'Shared driveway reseal brush applicator set', type: 'shared' },
  { text: 'Shared attic stair cover insulation R-49', type: 'shared' },
  { text: 'Shared garage door track alignment kit', type: 'shared' },
  { text: 'Shared home backup generator air filter replacement', type: 'shared' },
  { text: 'Shared driveway crack sealant melter rental', type: 'shared' },
  { text: 'Shared attic fan blade replacement set', type: 'shared' },
  { text: 'Shared garage door spring winding bars tool set', type: 'shared' },
  { text: 'Shared home backup battery disconnect switch kit', type: 'shared' },
  { text: 'Coffee at local cafe solo', type: 'personal' },
  { text: 'Personal lunch at work cafeteria', type: 'personal' },
  { text: 'Gym membership individual', type: 'personal' },
  { text: 'Spotify personal premium', type: 'personal' },
  { text: 'Haircut at barber shop', type: 'personal' },
  { text: 'Personal clothing purchase Zara', type: 'personal' },
  { text: 'Running shoes for marathon training', type: 'personal' },
  { text: 'Personal phone case accessory', type: 'personal' },
  { text: 'Video game purchase Steam', type: 'personal' },
  { text: 'Book purchase personal reading', type: 'personal' },
  { text: 'Concert ticket solo friend outing', type: 'personal' },
  { text: 'Uber ride to office alone', type: 'personal' },
  { text: 'Personal skincare products', type: 'personal' },
  { text: 'Manicure personal care', type: 'personal' },
  { text: 'Work lunch sandwich', type: 'personal' },
  { text: 'Office snacks personal', type: 'personal' },
  { text: 'Personal LinkedIn premium', type: 'personal' },
  { text: 'Online course for career development', type: 'personal' },
  { text: 'Professional certification exam fee', type: 'personal' },
  { text: 'Personal laptop accessory mouse', type: 'personal' },
  { text: 'Solo movie ticket cinema', type: 'personal' },
  { text: 'Personal hobby art supplies', type: 'personal' },
  { text: 'Birthday gift for friend', type: 'personal' },
  { text: 'Personal donation charity', type: 'personal' },
  { text: 'Taxi home after night out alone', type: 'personal' },
  { text: 'Personal vitamins supplements', type: 'personal' },
  { text: 'Sunglasses personal purchase', type: 'personal' },
  { text: 'Work shoes personal wardrobe', type: 'personal' },
  { text: 'Personal streaming Apple TV', type: 'personal' },
  { text: 'Mobile game in-app purchase', type: 'personal' },
  { text: 'Personal journal notebook', type: 'personal' },
  { text: 'Solo travel hostel booking', type: 'personal' },
  { text: 'Personal headphones AirPods', type: 'personal' },
  { text: 'Coffee Starbucks morning commute', type: 'personal' },
  { text: 'קפה בבוקר לבד', type: 'personal' },
  { text: 'ארוחת צהריים בעבודה', type: 'personal' },
  { text: 'מנוי לחדר כושר אישי', type: 'personal' },
  { text: 'תספורת במספרה', type: 'personal' },
  { text: 'קניות בגדים אישיות', type: 'personal' },
  { text: 'משחק מחשב אישי', type: 'personal' },
  { text: 'ספר לקריאה אישית', type: 'personal' },
  { text: 'כרטיס להופעה עם חבר', type: 'personal' },
  { text: 'נסיעת מונית לעבודה', type: 'personal' },
  { text: 'מוצרי טיפוח אישיים', type: 'personal' },
  { text: 'קורס אונליין לפיתוח קariéra', type: 'personal' },
  { text: 'מתנה ליום הולדת של חבר', type: 'personal' },
  { text: 'מנוי Spotify אישי', type: 'personal' },
  { text: 'Personal massage spa solo', type: 'personal' },
  { text: 'Solo hiking gear purchase', type: 'personal' },
  { text: 'Personal language app Duolingo', type: 'personal' },
  { text: 'Work conference ticket individual', type: 'personal' },
  { text: 'Personal wallet leather goods', type: 'personal' },
  { text: 'Solo brunch personal treat', type: 'personal' },
  { text: 'Personal photography equipment lens', type: 'personal' },
  { text: 'Personal nail polish cosmetics', type: 'personal' },
  { text: 'Solo beer at pub', type: 'personal' },
  { text: 'Personal cloud storage iCloud', type: 'personal' },
  { text: 'Personal audiobook Audible', type: 'personal' },
  { text: 'Personal dry cleaning suit', type: 'personal' },
  { text: 'Personal parking at event', type: 'personal' },
  { text: 'Personal meditation app Headspace', type: 'personal' },
  { text: 'Personal bicycle repair solo commute', type: 'personal' },
  { text: 'Personal tattoo studio', type: 'personal' },
  { text: 'Personal electronics repair phone screen', type: 'personal' },
  { text: 'Personal flowers bouquet gift self', type: 'personal' },
  { text: 'Personal parking fine ticket', type: 'personal' },
  { text: 'Personal VPN subscription', type: 'personal' },
  { text: 'Personal car wash solo vehicle', type: 'personal' },
  { text: 'Personal lottery ticket', type: 'personal' },
  { text: 'Personal museum entry solo visit', type: 'personal' },
  { text: 'Personal fast food drive through', type: 'personal' },
  { text: 'Personal ride share Bolt solo', type: 'personal' },
  { text: 'Personal stationery supplies', type: 'personal' },
  { text: 'Personal ice cream treat solo', type: 'personal' },
  { text: 'Personal domain name registration hobby', type: 'personal' },
  { text: 'Personal board game purchase', type: 'personal' },
  { text: 'Personal coffee beans specialty roast', type: 'personal' },
  { text: 'Personal watch band accessory', type: 'personal' },
  { text: 'Personal snack vending machine', type: 'personal' },
  { text: 'Personal fitness tracker band', type: 'personal' },
  { text: 'Personal podcast hosting fee', type: 'personal' },
  { text: 'Personal comic book store', type: 'personal' },
  { text: 'Personal energy drink convenience store', type: 'personal' },
  { text: 'Personal thrift store clothing find', type: 'personal' },
  { text: 'Personal plant for desk office', type: 'personal' },
  { text: 'Personal sushi takeout solo', type: 'personal' },
  { text: 'Personal parking app monthly', type: 'personal' },
  { text: 'Personal bubble tea drink', type: 'personal' },
  { text: 'Personal guitar strings music shop', type: 'personal' },
  { text: 'Personal magazine subscription', type: 'personal' },
  { text: 'Personal rideshare tip driver', type: 'personal' },
  { text: 'Personal craft beer six pack', type: 'personal' },
  { text: 'Personal emoji keyboard app', type: 'personal' },
  { text: 'Personal origami paper hobby', type: 'personal' },
  { text: 'Personal bubble bath products', type: 'personal' },
  { text: 'Personal sticker pack digital', type: 'personal' },
  { text: 'Personal fortune teller reading', type: 'personal' },
  { text: 'Personal enamel pin collection', type: 'personal' },
  { text: 'Personal vintage vinyl record', type: 'personal' },
  { text: 'Personal hot sauce bottle gourmet', type: 'personal' },
  { text: 'Personal tarot deck purchase', type: 'personal' },
  { text: 'Personal mechanical keyboard keycaps', type: 'personal' },
  { text: 'Personal artisan chocolate bar', type: 'personal' },
  { text: 'Personal fountain pen ink bottle', type: 'personal' },
  { text: 'Personal enamel mug camping gear', type: 'personal' },
  { text: 'Personal crochet yarn skein', type: 'personal' },
  { text: 'Personal bouldering day pass', type: 'personal' },
  { text: 'Personal specialty tea loose leaf', type: 'personal' },
  { text: 'Personal artisan soap bar', type: 'personal' },
  { text: 'Personal specialty hot sauce gift set self', type: 'personal' },
  { text: 'Personal enamel camping mug', type: 'personal' },
  { text: 'Personal enamel pin display board', type: 'personal' },
  { text: 'Personal enamel sticker sheet', type: 'personal' },
  { text: 'Personal enamel paint miniature hobby', type: 'personal' },
  { text: 'Personal enamel badge convention', type: 'personal' },
  { text: 'Personal enamel keychain souvenir', type: 'personal' },
  { text: 'Personal enamel brooch vintage shop', type: 'personal' },
  { text: 'Personal enamel trinket box', type: 'personal' },
  { text: 'Personal enamel charm bracelet add-on', type: 'personal' },
  { text: 'Personal enamel sign collectible', type: 'personal' },
  { text: 'Personal enamel badge pin fair', type: 'personal' },
  { text: 'Personal enamel coin purse', type: 'personal' },
  { text: 'Personal enamel thimble sewing', type: 'personal' },
  { text: 'Personal enamel cufflinks set', type: 'personal' },
  { text: 'Personal enamel tie clip vintage', type: 'personal' },
  { text: 'Personal enamel pill box travel', type: 'personal' },
  { text: 'Personal enamel compact mirror', type: 'personal' },
  { text: 'Personal enamel toothpick holder', type: 'personal' },
  { text: 'Personal enamel ash tray collectible', type: 'personal' },
  { text: 'Personal enamel matchbox cover', type: 'personal' },
  { text: 'Personal enamel stamp collection item', type: 'personal' },
  { text: 'Personal enamel spoon rest kitchen solo', type: 'personal' },
  { text: 'Personal enamel bookmark gift shop', type: 'personal' },
  { text: 'Personal enamel ring holder dish', type: 'personal' },
  { text: 'Personal enamel business card case', type: 'personal' },
  { text: 'Personal enamel pill organizer weekly solo', type: 'personal' },
  { text: 'Personal enamel valet tray desk', type: 'personal' },
  { text: 'Personal enamel snuff box antique', type: 'personal' },
  { text: 'Personal enamel pill cutter pharmacy', type: 'personal' },
  { text: 'Personal enamel tie bar gift self', type: 'personal' },
  { text: 'Personal enamel stamp album page', type: 'personal' },
  { text: 'Personal enamel pill reminder app premium', type: 'personal' },
  { text: 'Personal enamel pill wallet travel solo', type: 'personal' },
  { text: 'Personal enamel pill case keychain', type: 'personal' },
  { text: 'Personal enamel pill dispenser automatic solo', type: 'personal' },
  { text: 'Personal enamel pill splitter combo tool', type: 'personal' },
  { text: 'Personal enamel pill timer bottle cap', type: 'personal' },
  { text: 'Personal enamel pill pouch fabric travel', type: 'personal' },
  { text: 'Personal enamel pill box engraved gift self', type: 'personal' },
  { text: 'Personal enamel pill organizer monthly solo', type: 'personal' },
  { text: 'Personal enamel pill reminder watch band', type: 'personal' },
  { text: 'Personal enamel pill cutter pill splitter solo', type: 'personal' },
  { text: 'Personal enamel pill organizer large capacity solo', type: 'personal' },
  { text: 'Personal enamel pill case magnetic closure solo', type: 'personal' },
  { text: 'Personal enamel pill organizer stackable solo', type: 'personal' },
  { text: 'Personal enamel pill wallet keychain solo', type: 'personal' },
  { text: 'Personal enamel pill case pill splitter combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill cutter combo solo', type: 'personal' },
  { text: 'Personal enamel pill case engraved initials solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill timer combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill pouch combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill reminder watch combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill timer bottle combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill splitter safety combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill wallet RFID combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill reminder sticker combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill cutter timer combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill splitter timer combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill reminder timer combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill pouch timer combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill wallet timer combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill cutter reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill splitter reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill timer reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill pouch reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill wallet reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill cutter wallet reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill splitter wallet reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill timer wallet reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill pouch wallet reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill reminder wallet timer combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill cutter pouch wallet combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill splitter pouch wallet combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill timer pouch wallet combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill reminder pouch wallet combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill wallet pouch reminder combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill cutter splitter pouch wallet combo solo', type: 'personal' },
  { text: 'Personal enamel pill case pill timer splitter pouch wallet combo solo', type: 'personal' },
  { text: 'Personal enamel pill organizer pill reminder cutter splitter pouch wallet combo solo', type: 'personal' },
]

module.exports = { CLASSIFICATION_EXAMPLES }
